name: DockerBuild

on:
   push:
      branches: master
   pull_request:
      branches: master

jobs:
   build:
      runs-on: ubuntu-lates
      steps:
         -
          name: Checkout
          uses: actions/checkout@v2
         -
          name: Set Up Qemu
          uses: docker/setup-qemu-action@v1
         - 
          name: Set Up Docker Buildx
          uses: docker/setup-buildx-action@v1
         -
          name: Login into Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.MYDOCKER_TOKEN }}
         -
          name: Build and Push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64, linux/arm64
            push: true
            tag: eedy/python-helloworld:latest
            build-args: |
               arg1=value1
               arg2=value2
         -
          name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

